### PR TITLE
Make the capitalization of Execution Environment coherent

### PR DESCRIPTION
**Pull request by Fale**
My assumption is that the correct one would be "Execution Environment", since it is abbreviated "EE", but if the correct one is different, please let me know and I will change the PR to match the preferred capitalization.

### CODE REVIEW

**Comment by Shrews** [comment]
ping @acozine ... since you helped rewrite a lot of these docs, do you have any thoughts on this?

**Comment by Akasurde** [comment]
cc @samccann Could you please review this? Thanks in advance.

**Comment by samccann** [comment]
Hi @Fale and thanks for opening the docs PR!  So I would normally agree with you 100%. Unfortunately, we are a bit stuck. Execution environments from a Red Hat perspective, don't have capitalization.  Now the difficult part?  We as community have already gotten used to calling them EEs as an abbreviation for execution environments. I don't think we want to start calling them ees so we'll have to live with the discrepency at this point.

So I don't think we want to make the changes in this PR.

**Comment by Fale** [comment]
@samccann this is messy :-/

I think we should try to think the issue in 2 ways:
1. Should the community (ie: this website and many others) be implementing Red Hat's standard? (personally I think it would make sense)
2. If so, can we document those standards (also for Plyabooks vs playbooks, Inventory vs inventory, etc)? Creating a page about it would really help to start working in a standardized direction.

Interestingly enough, it seems like the "execution environment" capitalization memo was not received everywhere in Red Hat as well, since there are a lot of inconsistencies there as well.

**Comment by samccann** [comment]
@felixfontein valid points. My personal feeling is don't capitalize anything that isn't a specific product or project name.  (even tho that may differ from Red Hat's guidelines).  But i could go either way. 

I'll verify internally with RH writers about EEs and also see if they have a list we could..ahem..borrow for these decisions.

**Comment by samccann** [comment]
Thanks @Fale for your patience here as we dig into the details.

So official RH style is lowercase execution environment.  

Since we have attention here - should we stop calling them EEs and just spell out execution environment everywhere? @felixfontein @Andersson007 ?

**Comment by felixfontein** [comment]
I think using the abbreviation EE for execution environment is still useful. You don't always want to spell out the full name.

**Comment by Andersson007** [comment]
> Since we have attention here - should we stop calling them EEs and just spell out execution environment everywhere?

My opinion would be to use at  least at the beginning of each docs `execution environment (EE)` or `execution environment (hereinafter EE)` and then allow to use the abbreviation. It's OK using things like `FQCN`, etc. as it looks good to me and saves time:) Moreover, people often use the abbreviations in their speech.

I'm not against using `execution environment` instead but in this case we should use this approach everywhere (with things like FQCN too...)

**Comment by samccann** [comment]
no need for ``hereinafter` but otherwise agree, thanks

I opened a separate issue so we can formalize some of our terminology - https://github.com/ansible/ansible-documentation/issues/152

Thanks @Fale for getting the ball rolling on formalizing these terms. I'm closing this one since we have consensus to keep it lowercase (and keep EE) for now.

**Comment by samccann** [comment]
AAHAHAHA omgosh I have delusions of grandeur!  Since this isn't the main ansible docs, i don't get to close etc. So up to the builder folks to decide if they agree with us at this point.

**Comment by Shrews** [comment]
@samccann As you wish....  :)

**Pull request closed without merging**
