### PR TITLE
Remove github-workflows job

### PR DESCRIPTION
**Pull request by ssbarnea**

### CODE REVIEW

**Comment by ssbarnea** [comment]
@samdoran @Shrews Please gate. That is needed in order to remove github-worflows job from zuul.

**Review by Shrews — APPROVED** [review]

**Comment by samdoran** [comment]
recheck

**Comment by goneri** [comment]
recheck

**Comment by goneri** [comment]
Please remove the `Depends-On https://github.com/ansible/ansible-zuul-jobs/pull/1255` and merge this change.

**Comment by samdoran** [comment]
recheck

**Pull request merged**
