### PR TITLE
Fix ansible-builder --version command

### PR DESCRIPTION
**Pull request by pabelanger**
No longer use the hardcoded version string, we can look it up via PBR.

Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by shanemcd** [comment]
I don't love the idea of making PBR a runtime dependency. I just tested this and it seems to work (taken from [here](https://stackoverflow.com/questions/48383737/get-version-from-git-tags-through-pbr)):

```
>>> import pkg_resources
>>> version = pkg_resources.get_distribution('ansible_builder').version
>>> print(version)
0.5.1
```

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 6b326cdbffea10552835cbab7ff7f5ab6a25168c

**Comment by pabelanger** [comment]
> I don't love the idea of making PBR a runtime dependency. I just tested this and it seems to work (taken from [here](https://stackoverflow.com/questions/48383737/get-version-from-git-tags-through-pbr)):
> 
> ```
> >>> import pkg_resources
> >>> version = pkg_resources.get_distribution('ansible_builder').version
> >>> print(version)
> 0.5.1
> ```

Yah, there is some more functionality it includes, like getting pre-release version info

**Comment by AlanCoding** [comment]
closing with replacement

**Pull request closed without merging**
