### PR TITLE
DNM - testing repos

### PR DESCRIPTION
**Pull request by pabelanger**
Depends-On: https://github.com/ansible/python-builder-image/pull/44
Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now ccc81dc22996284d799c0223beee9cddfe7c922c

**Comment by pabelanger** [comment]
recheck

**Comment by samdoran** [comment]
Can this be closed?

**Pull request closed without merging**
