### PR TITLE
DNM - testing centos-8-stream images

### PR DESCRIPTION
**Pull request by pabelanger**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1050
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1049
Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by pabelanger** [comment]
recheck

**Comment by samdoran** [comment]
Can this be closed?

**Pull request closed without merging**
