### PR TITLE
Remove set-output syntax in GH workflow

### LINKED ISSUE #458: pulp_integration CI job needs updated to not use set-output
This job will break come June 1st, 2023. See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/ for more info.

### PR DESCRIPTION
**Pull request by Akasurde**
##### SUMMARY

* Use a new set of environment files to manage state
  and output provided by GH.

Fixes: #458

Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
.github/workflows/ci.yml

### CODE REVIEW

**Comment by Shrews** [comment]
Thanks for this. Seems good, but let's hold off on merging until the 2.0 work is merged because rebasing that PR to devel is a major pain.

**Comment by Akasurde** [comment]
Sure.

**Comment by Shrews** [comment]
This doesn't seem to work in my repo (which has the necessary secrets):

```
Error: Unable to process file command 'output' successfully.
Error: Invalid format 'has_secrets::true'
```

See https://github.com/Shrews/ansible-builder/actions/runs/4639846044/jobs/8211156771

**Review by Shrews — APPROVED** [review]
Yep, this works in my repo now.

**Comment by Shrews** [comment]
Will need a release_1.2 backport.

**Pull request merged**
