### PR TITLE
Introduction page: improve readability and structure

### PR DESCRIPTION
**Pull request by Andersson007**

### CODE REVIEW

**Comment by Andersson007** [comment]
cc @oraNod @samccann

**Comment by Andersson007** [comment]
cc @acozine

**Comment by samccann** [comment]
I posted this on a different PR but will repeat here - I disagree that spacing each sentence into it's own 'paragraph' makes things more readable.

**Comment by Andersson007** [comment]
> I posted this on a different PR but will repeat here - I disagree that spacing each sentence into it's own 'paragraph' makes things more readable.

@samccann thanks for the feedback
generally i think splitting long paragraphs (such those we can see in the original doc) improves readability (and desire to read and chances people finish reading each paragraph). Though maybe i did too much of splitting here in places where it would not bring any value, so I removed some spaces.
PTAL

**Comment by Andersson007** [comment]
@Akasurde can we merge this PR?

**Comment by Andersson007** [comment]
@samccann @Akasurde thank you!

**Pull request merged**
