### PR TITLE
 Supports line continuations for requirements.txt

### PR DESCRIPTION
**Pull request by akira6592**
#### SUMMARY

This PR allows [line continuations](https://pip.pypa.io/en/stable/reference/requirements-file-format/#line-continuations) by `\` for `requirements.txt`.

#### ISSUE TYPE

- Bugfix Pull Request

#### COMPONENT NAME

- src/ansible_builder/_target_scripts/introspect.py

### ADDITIONAL INFORMATION

related to:
  - https://github.com/ansible/ansible-builder/issues/593
  - https://github.com/PaloAltoNetworks/pan-os-ansible/issues/447

(Not a PR that solves all problems)

### CODE REVIEW

**Comment by Shrews** [comment]
Thanks for the PR.

However, I'm torn on whether or not to accept this and just demand a more rigid `requirements.txt` format for `ansible-builder`. Honestly, I'm leaning toward the latter to keep it simple for us. Looking at the pip code (https://github.com/pypa/pip/blob/49b9c0470f2a2a346293dd3bafc7c08f149db313/src/pip/_internal/req/req_file.py), they do a lot more processing of the requirements file that I'm not sure we should try to begin to duplicate, and we need to draw the line somewhere.

That being said, we are also aware that the requirements parsing library we are using is quite outdated and limited, and we need something better and more flexible. This is on our list to address in the future.

**Comment by akira6592** [comment]
@Shrews 
Actually, I was wondering how far I should implement.

Eventually, I would like to support line continuations and parse the `--hash` option as well. For `paloaltonetworks.panos` collection [`requirements.txt`](https://github.com/PaloAltoNetworks/pan-os-ansible/blob/v2.17.3/requirements.txt).

FYI, the `pip-requirements-parser` seemed to support line continuations and `--hash` option.

**Comment by nitzmahone** [comment]
Yeah, especially with `requirements-parser` looking somewhat dead, as a general policy I'm not feeling great about implementing a bunch of non-standard requirements grammar for even a subset of what pip supports- especially since we have to mash a bunch of these things together correctly in the end. Even something as seemingly simple as line-continuation actually complicates things we're planning, like being able to correlate a merged requirements entry to its source(s). I definitely understand the quality-of-life implications, but I also want to lean on standards for this stuff as much as is reasonably possible, and IIUC line continuation is not part of the defined standard.

**Comment by akira6592** [comment]
@nitzmahone 
Thank you for the information about the situation. 

Hoping that fundamental measures will be taken, I think I should close this PR.

**Comment by nitzmahone** [comment]
Closing per above

**Pull request closed without merging**
