### PR TITLE
Do installs in /usr/share directory to avoid user specific issues

### PR DESCRIPTION
**Pull request by AlanCoding**

### CODE REVIEW

**Comment by Spredzy** [comment]
This PR could be rrechecked once https://github.com/ansible/ansible-builder/pull/5 gets in

**Comment by AlanCoding** [comment]
recheck

**Comment by AlanCoding** [comment]
recheck

**Review by Spredzy — APPROVED** [review]

**Review by beeankha — APPROVED** [review]
🚀

**Pull request merged**
